// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Db;

namespace Server.Db.Migrations
{
    [DbContext(typeof(BookmarkContext))]
    [Migration("20210729132155_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Server.Db.BookmarkContext+Bookmark", b =>
                {
                    b.Property<int>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("AuthorSnowflake")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChannelSnowflake")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MessageSnowflake")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserSnowflake")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("UserSnowflake1")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("BookmarkId");

                    b.HasIndex("UserSnowflake1");

                    b.HasIndex("MessageSnowflake", "UserSnowflake")
                        .IsUnique();

                    b.ToTable("Bookmark");
                });

            modelBuilder.Entity("Server.Db.BookmarkContext+User", b =>
                {
                    b.Property<decimal>("UserSnowflake")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("UserSnowflake");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Db.BookmarkContext+Bookmark", b =>
                {
                    b.HasOne("Server.Db.BookmarkContext+User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserSnowflake1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Db.BookmarkContext+User", b =>
                {
                    b.Navigation("Bookmarks");
                });
#pragma warning restore 612, 618
        }
    }
}
